11.WEB/1023/DBWEB/models/models.py
#-----
# 데이터베이스 테이블 정의 클래스
#-----

#모듈 로딩
from DBWEB import db

# Question 테이블 정의 클래스
class Question(db.Model):
    #컬럼 정의
    id=db.Column(db.Integer,primary_key=True)
    subject=db.Column(db.String(200),nullable=False)
    content=db.Column(db.Text(),nullable=False)
    create_date=db.Column(db.DateTime(),nullable=False)


# Answer 테이블 정의 클래스
class Answer(db.Model):
    #컬럼 정의
    id=db.Column(db.Integer,primary_key=True)
    question_id=db.Column(db.Integer,db.ForeignKey('question.id',ondelete='CASCADE'))
    question=db.relationship('Question',backref=db.backref('answer_set', ))
    content=db.Column(db.Text(),nullable=False)
    create_date=db.Column(db.DateTime(),nullable=False)

11.WEB/1023/DBWEB/__init__.py
#-----------------
# Flask Framework에서 WebServer 구동 파일
# - 파일명: app.py
#-----------------

#모듈 로딩
from flask import Flask

#db 관련 설정
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import config

db=SQLAlchemy()
migrate=Migrate()       #db 컨트롤러


#사용자 정의 함수
def create_app():

    #전역변수
    # - Flask Web Server 인스턴스 생성
    APP=Flask(__name__)
    
    #db 관련 초기화 설정
    APP.config.from_object(config)


    #db 초기화 및 연동
    db.init_app(APP)
    migrate.init_app(APP,db)

    #db 클래스 정의 모듈
    from .models import models
    

    # #url(클라이언트 요청 페이지) 주소를 보여주는 기능의 함수
    # def printPage():
    #     return '<h1>하잉 😶‍🌫️</h1>'

    # #url 함수 연결
    # APP.add_url_rule('/',view_func=printPage,endpoint='INDEX')

    # #위의 단계를 한번해 해결하려면
    # @APP.route('/',endpoint='INDEX')
    # def printPage():
    #     return '<h1> 😶‍🌫️ 하잉 😶‍🌫️ </h1>'

    #url 처리 모듈 등록 - 블루프린트 관련
    from.views import main_view,answer_views
    APP.register_blueprint(main_view.main_bp)
    APP.register_blueprint(answer_views.ans_bp)

    return APP


#조건부 실행
if __name__ == '__main':
    #flask web server 구동
    app=create_app()
    app.run

11.WEB/1023/DBWEB/views/answer_views.py
from datetime import datetime

from flask import Blueprint,url_for,request
from werkzeug.utils import redirect

from DBWEB import db
from DBWEB.models.models import Question,Answer

ans_bp=Blueprint('answer',__name__,url_prefix='/answer')

@ans_bp.route('/create/<int:question_id>',methods=('POST',))
def create(question_id):
    question=Question.query.get_or_404(question_id)
    content=request.form['content']
    answer=Answer(content=content,create_date=datetime.now())
    question.answer_set.append(answer)
    #db.session.add(answer)
    db.session.commit()
    return redirect(url_for('MAIN.detail',question_id=question_id))

11.WEB/1023/DBWEB/views/main_view.py
#------
#Flask Framework에서 모듈 단위 url 처리 파일
#-----

#모듈 로딩
from flask import Blueprint,render_template
from DBWEB.models.models import Question

#blueprint 인스턴스 생성
main_bp=Blueprint('MAIN',import_name=__name__,
                  url_prefix='/',
                  template_folder='templates')

#url 처리 라우팅 함수
@main_bp.route('/')
def index():
    return render_template('index.html',name='@dlrj_rlaudwn')

@main_bp.route('/qlist/')
def printList():
    #db에서 조회한 결과를 html 파일로 전달
    q_list=Question.query.all()
    return  render_template('question/question_list.html', question_list=q_list)

@main_bp.route('/qdetail/<int:question_id>')
def detail(question_id):
    #db에서 조회한 1개의 question 인스턴스를 html 파일로 전달
    question=Question.query.get(question_id)
    return  render_template('question_detail.html', question=question)

11.WEB/1023/DBWEB/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>😶‍🌫️</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
</head>
<body>
    <h1>🍀 good luck 🍀</h1>

    {{name}} 내 자리 내놔잉😒😒
</body>
</html>

11.WEB/1023/DBWEB/templates/question_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>😶‍🌫️</title>
</head>
<body>
    <h1>질문 상세보기</h1>
    <div id="qDiv">
        <label>subject: </label>
        {{question.subject}} <br><br>

        <label>content: </label>
        {{question.content}} <br>
        <br>
    </div>

    <div>
        <form action="{{url_for('answer.create',question_id=question.id)}}" method="POST">
            <textarea name="content" id="content" rows="15" placeholder="답글 입력"></textarea>
            <input type="submit" value="등록">
        </form>
    </div>

    <h5>{{question.answer_set|length}}개의 답변이 있습니다.</h5>
    <div>
        <ul>
            {% for answer in question.answer_set %}
            <li>{{answer.content}}</li>
            {% endfor %}
        </ul>
    </div>

</body>
</html>

11.WEB/1023/DBWEB/templates/question_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        th, td {border: 1px solid black;
                border-collapse: collapse;}
    </style>
</head>
<body>
    <h1>질문 게시판</h1>
    <!-- ver 1. 테이블 형태 -->
    <table>
        <tr>
            <th>id</th>
            <th>subject</th>
            <th>content</th>
            <th>date</th>
        </tr>
        {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>
                    <a href="/qdetail/{{question.id}}">{{question.id}}</a>
                </td>
                <td>{{question.subject}}

                </td>
                
                <td>{{question.content}}</td>
                <td>{{question.create_date}}</td>
            </tr>
            {% endfor %}
        {% else %}
        <tr>
            <td class="msg" colspan="3"> 등록된 질문이 없습니다. </td>
        </tr>
        {% endif %}
    </table>
    
    <br><hr>

    <!-- ver 2. 리스트 형태 -->
    {% if question_list %}
        <!--
        <li>{{name}}</li>
        <li>{{name}}</li>
        <li>{{name}}</li>
        <li>{{name}}</li> 
        이렇게 하면 고정된 질문만 되니까 동적으로 개수 변하게 해야 함 => 반복문 사용
        -->
        {% for question in question_list %}
        <ol> 
            <li>{{question.id}}</li>
            <li>{{question.subject}}</li>
            <li>{{question.content}}</li>
            <li>{{question.create_date}}</li>
        </ol>
        {% endfor %}
    {% else %}
        <p class="msg">등록된 질문이 없습니다</p>
    {% endif %}
</body>
</html>